### ISSUE TITLE
Grid view?

### ISSUE THREAD

**Issue by KSXGitHub** [Skycoder42/IconThemeBrowser#1]
Icon shapes only fit a square, long rectangles in current list view is redundant.

**Comment by Skycoder42** [comment]
I don't really agree with you, as a grid-like list would lead to unreadable icon names - and at least for me these are important to see as well. Also, I personally think a listview is more readable then a grid, but thats just a personal preference.

If you want, you can create a PR that allows one to dynamically switch between a list and a grid, that would be fine with me.
